# Generated by Django 4.1.7 on 2023-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=100)),
                ('classnumber', models.CharField(max_length=100)),
                ('classlink', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
